### ISSUE TITLE
Does Eclipse Lyo support OAuth 2.0

### ISSUE THREAD

**Issue by goutham-n** [eclipse/lyo.server#37]
Hello Experts, 
Does Eclipse Lyo support OAuth 2.0, read some where latest version support OAuth 2.0.
If it doesn't, which libraries do you suggest to use with Eclipse Lyo OSLC for OAuth 2.0 implementation?

Thanks,
Goutham

**Comment by jadelkhoury** [comment]
Hi Gouthan

Lyo does not yet support OAuth 2.0. It would be a great lift for Lyo, but I am not aware of any efforts to do so at the moment.

Not sure what you read, but the [OSLC 3.0 Specs](http://docs.oasis-open.org/oslc-core/oslc-core/v3.0/csprd03/part1-overview/oslc-core-v3.0-csprd03-part1-overview.html#authentication), suggests using OAuth 2.0. Could that be it.

And as OSLC 3.0 suggest, I'd consider adopting  [OpenIDConnect](https://openid.net/connect/) Which is a bit more than Oauth 2.0.
But if you are working on an integration, it is probably more important to consider what your client/server you are working against is using.
