### ISSUE TITLE
Googlecode.com has nothing for oauth

### ISSUE THREAD

**Issue by twocs** [eclipse/lyo.server#38]
Repositories in webapp's pom.xml (https://github.com/eclipse/lyo.server/blob/master/oauth-webapp/pom.xml)
http://oauth.googlecode.com/svn/code/maven

When I try it, there's nothing at the address.

> 404. That’s an error.
> 
> The requested URL /svn/code/maven was not found on this server. That’s all we know.

So I'm trying to figure out, is this just a temporary issue? If not, then what's a suitable replacement for this? Is that the same as this? https://mvnrepository.com/artifact/net.oauth.core/oauth

**Comment by jadelkhoury** [comment]
It could well be temporary. But are you facing a particular error when building the project? 
I am not sure why we are using http://oauth.googlecode.com/svn/code/maven when it is available on mvnrepository.

As you can see in the parent pom.xml file (https://github.com/eclipse/lyo.server/blob/c996688a24ba39d56be441b2a592390ec30e55c3/pom.xml#L28), it is the 20100527 version we are using. 

So, worth replacing or removing this repository url property, and see if it works better.

**Comment by berezovskyi** [comment]
http://oauth.googlecode.com/svn/code/maven is as dead as it could be. The artifact in question is loaded from other repos and the build is OK: https://github.com/eclipse/lyo.server/runs/1377172446?check_suite_focus=true

closing as there is nothing to do
